name: newsletter_form
description: Newsletter form using lyform package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  lyform: ^0.9.2
  lyform_validators: ^0.7.2

dev_dependencies:
  bloc_test: ^9.0.3
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
